### ISSUE TITLE
Exception during install

### ISSUE THREAD

**Issue by nikolay-borzov** [ceri-comps/ceri-icon#5]
I'm getting the following exception when calling `npm i -D ceri-icon`.
My node version is `6.11.4`

```
> ceri-icon@0.2.3 install C:\my_project\node_modules\ceri-icon
> node ./lib/icon-normalizer.js


Normalizing and optimizing SVG Icons for ceri-icon
E:\drill\drill-ui-core\node_modules\handle-that\lib\_worker.js:5
process.on("message", async({pieces, current, length}) => {
                           ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by paulpflug** [comment]
Which node version are you using? I think, Node 8 is required for async 
functions..

**Comment by nikolay-borzov** [comment]
I used `6.11.14`. I managed to install `ceri-icon` after switching to Node `8.7.0`. Perhaps we should mention this requirement somewhere.
